### ISSUE TITLE
xlsx preview not working

### ISSUE THREAD

**Issue by akashgundaniya** [raafacachoeira/jquery-file-viewer#1]

**Comment by raafacachoeira** [comment]
Hi, this implementation does not support the xlsx file. 
Here all supported formats: 
`  $.fn.fileViewer.defaults.map = {
        extension: {
            '.pdf': 'pdf',
            '.txt': 'text',
            '.htm': 'html',
            '.html': 'html',
            '.ogg': 'video',
            '.webm': 'video',
            '.mp4': 'video',
            '.mov': 'video',
            '.vgg': 'video',
            '.jpg': 'image',
            '.jpeg': 'image',
            '.apng': 'image',
            '.png': 'image',
            '.bmp': 'image',
            '.svg': 'image',
            '.tif': 'image',
            '.mp3': 'audio',
            '.wav': 'audio'
        },
        contentType: {
            'text/html': 'html'
        }
    }`

Anything else, it will render the default component "File not Supported!!"


You can extend like that

Add implementation
`
$.fn.fileViewer.defaults.viewers.excel = {
    id: 'excel-viewer',
    class: 'excel-viewer',
    render: function (file) {
        return ''; /*Add here a excel template render*/
    }
}
`

Add map to find implementation
`$.extend($.fn.fileViewer.defaults.map.extension, { '.xlsx': 'excel'}) `

**Comment by akashgundaniya** [comment]
Thank You For Update But now i modified code and it working fine

Thanks
Akash
